name: Rails tests

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    # Service containers to run with `runner-job`
    services:
      postgres:
        image: postgres:11
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Install PostgreSQL 11 client
        run: |
          sudo apt-get -yqq install libpq-dev

      - name: Bundle install
        run: |
          gem install bundler -v '2.1.4'
          bundle install --jobs 4 --retry 3

      - name: Setup Database
        env:
          PGHOST: localhost
          PGUSER: postgres
          PGPASSWORD: postgres
          RAILS_ENV: test
        run: |
          bundle exec rails db:setup

      - name: Run tests
        env:
          PGHOST: localhost
          PGUSER: postgres
          PGPASSWORD: postgres
          RAILS_ENV: test
        run: COVERAGE=true bundle exec rspec --require rails_helper

      - name: Run code analysis
        run: bundle exec rake code_analysis

      - name: Upload coverage results
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: coverage-report
          path: coverage
